### ISSUE TITLE
More Info button interprets HTML even if email was sent without HTML enabled

### ISSUE THREAD

**Issue by csalzano** [JWardee/wp-mail-catcher#122]
This plugin will lead users to believe an HTML email was sent even if the email was sent without the HTML content type set. I'm using it to build a plugin, and while the first few actual emails look terrible because I had not yet used the `wp_mail_content_type` hook to enable HTML in emails, the More Info button interpreted the HTML. It wasn't until I actually sent real tests that I discovered I was sending a bunch of HTML in a plain text email. Thanks for reading!

**Comment by JWardee** [comment]
Should be solved in 20d2d18c10a4e1933cb8b3b2b2e56cacadfaa99a
