### ISSUE TITLE
Changing from another mail catcher

### ISSUE THREAD

**Issue by RobGH** [JWardee/wp-mail-catcher#127]
We are currently using "Email Log", which is very limiting as well as expensive to get the same capability as you have here in this very fine WP plugin.

Question: If we do not purge/delete the existing log, remove the plugin and then install WP Mail Catcher, will WP Mail Catcher be able to see the existing notifications? I do not know if Email Log conforms to WP standards, but the assumption is that it does (as most do).

If you could give us a quick response, we would be very thankful - thank you in advance!!!

**Comment by JWardee** [comment]
Glad to hear you like the plugin! When you uninstall the plugin all the email logs are deleted, so if you then re-install it you'll have a "clean slate". However if the plugin is just deactivated then the logs will be there when the plugin is re-activated. Hope that makes sense!

**Comment by RobGH** [comment]
I'm not sure I understand your response. At present, only Email Log is installed. They have an option to delete or not delete the log when uninstalling their plugin (I will tell it to not delete the log). If I do so, leaving the email log in place, and then install WP Mail Catcher --- this is my question now --- will WP Mail Catcher be able to see the log?

Our goal with changing to WP Mail Catcher is to preserve and continue managing the email logs created by Email Log, but now with WP Mail Catcher. We are hoping this will work!
