### ISSUE TITLE
Resend HTML message not supported

### ISSUE THREAD

**Issue by zoro707** [JWardee/wp-mail-catcher#130]
## Expected Behaviour

HTML format should be supported when resending emails.

## Current Behaviour

The resend button doesn’t support HTML message format and the re-sent message is totally un-readable without HTML support (message shows as a lot of html tags instead of a readable HTML formatted message).

## My Environment
- WordPress version: 5.9.2
- PHP version: 7.4.28
- Plugins I have installed: X, Y, Z

## Steps to Reproduce

1.
2.
3.
4.

**Comment by JWardee** [comment]
Solved in 20d2d18c10a4e1933cb8b3b2b2e56cacadfaa99a
