### ISSUE TITLE
Scroll does not work on mobile or ipad

### ISSUE THREAD

**Issue by Nemi5150** [JWardee/wp-mail-catcher#131]
## Expected Behaviour

When viewing an email on android phone or Ipad, horizontal scrolling the html email does work when the viewport is smaller than size of the email. 

## My Environment
- WordPress version: X
- PHP version: X
- Plugins I have installed: X, Y, Z

## Steps to Reproduce

1. Open an email that is larger than the viewport
2. No horizontal scroll bars are present and scrolling is impossible. 
3.
4.

**Comment by Nemi5150** [comment]
More info: in my testing, this behavior goes away on my Windows test machine when changing the `width` attribute on the `modal-content` div.

Simply changing width to 80% from the default 800px allows for horizontal scrollbars when the page width goes below 800px. 

The exact class I am changing is: `.wp-mail-catcher-page .modal .modal-content.is-html`

Screenshots attached
![mail1](https://user-images.githubusercontent.com/5833302/161782512-9f71e59f-aac0-4764-9f04-91a75c170cef.PNG)
![mail2](https://user-images.githubusercontent.com/5833302/161782527-9bee1c6a-825d-498e-bec2-20bba1c14467.PNG)

**Comment by JWardee** [comment]
A fix for this will be available in the next version :)
