### ISSUE TITLE
"New Message" button doesn't work

### ISSUE THREAD

**Issue by AlecRust** [JWardee/wp-mail-catcher#146]
## Expected Behaviour

Not entirely sure what this button is supposed to do, but it doesn't work.

## Current Behaviour

Clicking this button does nothing:

![image](https://user-images.githubusercontent.com/247634/173239483-d20749b5-71a7-40d8-8952-686e2429f980.png)

There's also a 404 in the console:

```
GET https://www.sitename.com/wp-content/plugins/wp-mail-catcher/assets/global.min.js?v=2.0.0&ver=6.0 net::ERR_ABORTED 404
```

## My Environment
- WordPress version: 6.0
- PHP version: 8.0
- Plugins I have installed: A bunch

## Steps to Reproduce

1. Install plugin
2. Navigate to email logs
3. Click "New Message" button

## Possible Solution

Fix the 404.

**Comment by JWardee** [comment]
Hey Alec, thanks for the quick report! Turns out that SVN didn't upload that file - if you delete the plugin and reinstall it you should be good to go!
