### ISSUE TITLE
Clarify supported plugins

### ISSUE THREAD

**Issue by AlecRust** [JWardee/wp-mail-catcher#147]
- Does this plugin support the popular [Sendinblue](https://wordpress.org/plugins/mailin/) plugin? The Sendinblue plugin is a pretty comprehensive email
- Are we sure [Post SMTP](https://wordpress.org/plugins/post-smtp/) plugin is not supported? What about when it's using SendGrid API?

**Comment by JWardee** [comment]
Mail catcher should work with the majority of plugins out of the box. Unless they change how the `wp_mail` function works, or not implementing all the actions/filters that `wp_mail` uses by default.

This is the issue with Post SMTP. Support can be added - it just needs some extra code to hook up to the changes Post SMTP makes which I may get to depending on demand or I'm happy to have a PR to add support.

As for SendInBlue, install it and see if it works and as above if there are issues I can look into adding support (if there are enough people who need it) or accept a PR that adds support.

Hope that helps!

**Comment by AlecRust** [comment]
> This is the issue with Post SMTP. Support can be added - it just needs some extra code to hook up to the changes Post SMTP makes which I may get to depending on demand or I'm happy to have a PR to add support.

To be clear, in my testing emails sent by Post SMTP are logged in WP Mail Catcher. I assume this is because I'm using SendGrid. Which tbh I assume most PostSMTP users do (or some 3rd party like it).
