### ISSUE TITLE
Bug in mail cleanup

### ISSUE THREAD

**Issue by Nemi5150** [JWardee/wp-mail-catcher#148]
## Expected Behaviour

Getting the following error when manually running mail cleanup, OR when running the cron job. 

[12-Jun-2022 16:39:00 UTC] WordPress database error Commands out of sync; you can't run this command now for query SELECT *, CASE 
WHEN `type` = 3 THEN 0
WHEN `type` = 4 THEN 1
WHEN `type` = 7 THEN 2
WHEN `type` = 6 THEN 3
WHEN `type` = 5 THEN 4
WHEN `type` = 9 THEN 5
WHEN `type` = 8 THEN 6
WHEN `type` = 2 THEN 7
WHEN `type` = 1 THEN 8
ELSE 9999
END AS `typeSort`, CASE 
WHEN `type` = 3 THEN `parameters`
WHEN `type` = 4 THEN `parameters`
WHEN `type` = 1 THEN `IP`
WHEN `type` = 9 THEN `IP`
WHEN `type` = 5 THEN `IP`
WHEN `type` = 6 THEN `IP`
WHEN `type` = 7 THEN `IP`
WHEN `type` = 2 THEN `IP`
WHEN `type` = 8 THEN `IP`
ELSE 9999
END AS `detailSort`
 FROM `wp_wfBlocks7` WHERE `type` IN (3) AND (`expiration` = 0 OR `expiration` > UNIX_TIMESTAMP()) ORDER BY `typeSort` ASC, `id` DESC made by wfShutdownRegistry->handleShutdown, wfShutdownFunction->invoke, wfWAFIPBlocksController::synchronizeConfigSettings, wfBlock::countryBlocks, wfBlock::allBlocks
[12-Jun-2022 16:39:00 UTC] WordPress database error Commands out of sync; you can't run this command now for query SELECT *, CASE 
WHEN `type` = 3 THEN 0
WHEN `type` = 4 THEN 1
WHEN `type` = 7 THEN 2
WHEN `type` = 6 THEN 3
WHEN `type` = 5 THEN 4
WHEN `type` = 9 THEN 5
WHEN `type` = 8 THEN 6
WHEN `type` = 2 THEN 7
WHEN `type` = 1 THEN 8
ELSE 9999
END AS `typeSort`, CASE 
WHEN `type` = 3 THEN `parameters`
WHEN `type` = 4 THEN `parameters`
WHEN `type` = 1 THEN `IP`
WHEN `type` = 9 THEN `IP`
WHEN `type` = 5 THEN `IP`
WHEN `type` = 6 THEN `IP`
WHEN `type` = 7 THEN `IP`
WHEN `type` = 2 THEN `IP`
WHEN `type` = 8 THEN `IP`
ELSE 9999
END AS `detailSort`
 FROM `wp_wfBlocks7` WHERE `type` IN (1, 8, 9, 2, 5, 6) AND (`expiration` = 0 OR `expiration` > UNIX_TIMESTAMP()) ORDER BY `typeSort` ASC, `id` DESC made by wfShutdownRegistry->handleShutdown, wfShutdownFunction->invoke, wfWAFIPBlocksController::synchronizeConfigSettings, wfBlock::ipBlocks, wfBlock::allBlocks
[12-Jun-2022 16:39:00 UTC] WordPress database error Commands out of sync; you can't run this command now for query SELECT *, CASE 
WHEN `type` = 3 THEN 0
WHEN `type` = 4 THEN 1
WHEN `type` = 7 THEN 2
WHEN `type` = 6 THEN 3
WHEN `type` = 5 THEN 4
WHEN `type` = 9 THEN 5
WHEN `type` = 8 THEN 6
WHEN `type` = 2 THEN 7
WHEN `type` = 1 THEN 8
ELSE 9999
END AS `typeSort`, CASE 
WHEN `type` = 3 THEN `parameters`
WHEN `type` = 4 THEN `parameters`
WHEN `type` = 1 THEN `IP`
WHEN `type` = 9 THEN `IP`
WHEN `type` = 5 THEN `IP`
WHEN `type` = 6 THEN `IP`
WHEN `type` = 7 THEN `IP`
WHEN `type` = 2 THEN `IP`
WHEN `type` = 8 THEN `IP`
ELSE 9999
END AS `detailSort`
 FROM `wp_wfBlocks7` WHERE `type` IN (7) AND (`expiration` = 0 OR `expiration` > UNIX_TIMESTAMP()) ORDER BY `typeSort` ASC, `id` DESC made by wfShutdownRegistry->handleShutdown, wfShutdownFunction->invoke, wfWAFIPBlocksController::synchronizeConfigSettings, wfBlock::lockouts, wfBlock::allBlocks

## My Environment
- WordPress version: X
- PHP version: X
- Plugins I have installed: X, Y, Z

## Steps to Reproduce

1.
2.
3.
4.

**Comment by Nemi5150** [comment]
Get this as well


Fatal error: Allowed memory size of 268435456 bytes exhausted (tried to allocate 77824 bytes) in /home/changi31/public_html/wp-includes/wp-db.php on line 2162

**Comment by Nemi5150** [comment]
For what it is worth, I deleted the plugin and reinstalled and did a test cleanup and it no longer has an error.

**Comment by JWardee** [comment]
Hey @Nemi5150, it looks like your using some kind of block plugin that's using up all your memory before mail catcher can run the clean up. It's not an issue with mail catcher, you can either: [increase your memory limit](https://www.wpbeginner.com/wp-tutorials/fix-wordpress-memory-exhausted-error-increase-php-memory/) or deactivate other plugins.

It may occasionally work but it won't be consistent and the issue will get worse if you install more plugins. Hope that helps! :)

**Comment by Nemi5150** [comment]
Ok, but I don’t run any block plugins. I keep plugins to a minimum, other than woocommerce.

**Comment by JWardee** [comment]
That's good, I only say block plugins because it looked like it failed on querying the `wp_wfBlocks7` table which I assumed was to do with a block plugin but it looks like a table used by Wordfence. In either case the options I outlined above will help you address the issue.

**Comment by Nemi5150** [comment]
I am still getting a DB out of memory when this runs. It did not do it before nor do I have any other problems. Did you change your DB query to something inefficient? Given the number of emails in my log I find it hard to believe that this is making the DB run out of memory. Something is amiss. I will have to roll back to the previous version.
