### ISSUE TITLE
Email address not displaying in the "To" column

### ISSUE THREAD

**Issue by AlecRust** [JWardee/wp-mail-catcher#153]
## Expected Behaviour

I want to always see the full value of `To`.

## Current Behaviour

If `To` is just `email@domain.com` it works, if `To` is formatted like `name <email@domain.com>` then only `name` shows:

<img width="800" alt="image" src="https://user-images.githubusercontent.com/247634/174572511-9ab77632-7301-4459-96be-325ac5a0c838.png">

It looks like the `<email@domain.com>` part is actually in the HTML, it's just not being escaped so it's actually part of the HTML 🙂 

## My Environment
- WordPress version: 6.0
- PHP version: 8.0
- Plugins I have installed: Stuff

## Possible Solution

Escape the values so that `name <email@domain.com>` is displayed in this case instead of just `name`.

**Comment by JWardee** [comment]
Nice spot! Will be fixed in the next patch

**Comment by JWardee** [comment]
Fixed in 73283cf
