### ISSUE TITLE
Double template when resending

### ISSUE THREAD

**Issue by tezalsec** [JWardee/wp-mail-catcher#170]
I have the popular ’email_templates’ plugin installed which allows you to give all sent out emails a default look. Your plugin’s resend function however repeats this theming rendering a double template, an email within an email. Although I understand the current logic, would it be possible to make the resend function bypass or block any applying of theming so the resend email really is a copy of the original, instead of an email within an email?

from: https://wordpress.org/support/topic/double-template-when-resending/#post-16130339 
other plugin: https://wordpress.org/plugins/email-templates/

**Comment by JWardee** [comment]
Thanks for reporting this. I've had a look into it and there isn't alot that can be done. The `email-templates` plugin uses the `wp_mail` hook and adds its template just before the email is sent. This issue would also crop up on other plugins that offer a resend function. Ideally the `email-templates` plugin would embed a flag (like a html comment, data attribute) or something and only apply its template if that flag isn't there, that way all email plugins that happen to save and resend email wouldn't have the html applied twice. But that's entirely up to them if they deem it worth doing.

If there's sufficient demand I can take another look and see if I can figure something out. But for now I'm going to close this issue. If you'd like to submit a PR that can reliably resolve the issue then I'd be happy to take a look :)

Sorry for the bad news but I hope that makes sense! :)
