### ISSUE TITLE
Log detail modal shows raw HTML

### ISSUE THREAD

**Issue by JWardee** [JWardee/wp-mail-catcher#187]
Needs investigation. Issue only occurs since 2.1.3 patch.

[Thread](https://wordpress.org/support/topic/log-viewer-showing-html-encoded-message/)

**Comment by King-Rings** [comment]
Within the modal's  iFrame, there are <html><body> elements (always have been) but version 2.1.3 introduced an entirely new document (<!DOCTYPE html>) inside the <body> which causes an overflow. The result is that I see raw html output to the modal window. I can observe this result in both Firefox Developer and Chrome (current versions).

![image](https://github.com/JWardee/wp-mail-catcher/assets/96193045/2600680b-55e9-4eaf-bb73-5b0e0120dcdc)

As you know, version 2.1.2 has a documented cross-site scripting vulnerability. Despite this risk, I have been using this old version anyway but my Hosting service has begun to complain (rightfully).

I see this bug listed in the 2.1.5 Milestones, when should we expect release? Thank you!

**Comment by JWardee** [comment]
Hi @King-Rings, thanks for the extra info! 

Would you mind sending me a screenshot of the "detail" and "debug" tabs in the log and would it be possible for you to send me through a copy of the email html along with any headers that were sent with it (please replace any sensitive info in the email with dummy data). Feel free to either paste it here or email me directly at wordpress@jamesward.io.

I'm not sure on a timeline at the moment, I'll try to make a start on 2.1.5 this weekend but I can't make any promises. Feel free to have a go at fixing the issue yourself and submitting a PR if you'd prefer :)

**Comment by JWardee** [comment]
Hey @King-Rings, just letting you know I've received your email - thank you for sending that through! I'll respond back here when I have an update

**Comment by JWardee** [comment]
Hey @King-Rings, would you mind trying out this draft release, it should resolve your issue but just want to be sure before publishing it to everyone

https://github.com/JWardee/wp-mail-catcher/releases/tag/untagged-cac2392f5d1cd13ee89a

**Comment by King-Rings** [comment]
Sure, I'll try it but the provided link give me a 404 error and I cannot locate the update under Releases or Tags. Maybe a permissions thing, are the untagged releases public?

**Comment by JWardee** [comment]
Ah I see what you mean, give it a ago now: https://github.com/JWardee/wp-mail-catcher/releases/tag/v2.1.5

**Comment by King-Rings** [comment]
Tested on both [very minimal] staging site and fully active production site, issue resolved! Thanks for the quality work, James.

**Comment by JWardee** [comment]
Perfect thanks for that, I've released that patch!
