### ISSUE TITLE
values in the time column of the mail logs are off by the gmt_offset

### ISSUE THREAD

**Issue by pbiron** [JWardee/wp-mail-catcher#41]
As far as I can tell, you are storing the GMT time an email was sent in the `wp_mail_catcher_logs` table.

However in the `time (Sent)` column of the list table, you are displaying the `human_time_diff()` from local time.

For example, I'm in MST (-6 from UTC).  When I send a "New Message" and then immediately look at the list table, that message shows it was sent "6 hours ago".

I can do a PR with a fix if you accept them.

**Comment by JWardee** [comment]
Fixed in #45 please re-open if this is still an issue

**Comment by pbiron** [comment]
would you like me to check that these are fixed before you release the next version in the .org repo?  I'm really busy for the next 3-4 days, and so probably won't be able to get to it until things clear up...if you're dying to release the next version quickly.

**Comment by JWardee** [comment]
If you get a chance to retest that would be great, I'm aiming for a release this Saturday so if you could test before then that's great but if not then that's not a problem :)

**Comment by pbiron** [comment]
I should be able to retest by Sat.  thanx.

**Comment by pbiron** [comment]
I downloaded the 1.2.4 branch, built it locally and can confirm that the values in the `time (Sent)` column are now displaying in my local time and not GMT.
