### ISSUE TITLE
sorting the list table by a particular column has no effect

### ISSUE THREAD

**Issue by pbiron** [JWardee/wp-mail-catcher#42]
No matter what column I sort by, the rows in the list table are always ordered by `time DESC`.

See the following screenshots, where the first is ordered by `to DESC` and the second is by `to ASC`...notice that the rows are in the same order in both cases

![to-desc](https://user-images.githubusercontent.com/3824560/55591524-f1c7fa80-56f2-11e9-962f-d927f13589c7.png)
![to-asc](https://user-images.githubusercontent.com/3824560/55591536-f9879f00-56f2-11e9-8f08-d752e7429420.png)

I can also do a PR with a fix for this one.

**Comment by JWardee** [comment]
Fixed in #45 please re-open if this is still an issue

**Comment by pbiron** [comment]
I downloaded the 1.2.4 branch, built it locally and can confirm that sorting the list table is now functioning correctly.
