### ISSUE TITLE
why do you include your own copy of WP_List_Table?

### ISSUE THREAD

**Issue by pbiron** [JWardee/wp-mail-catcher#43]
I'm sure there is a reason, but I can't fathom what it is.

One consequence of not using the standard `WP_List_Table` as the base class for `MailAdminTable` is that the markup and styling of the pagination links in core's `WP_List_Table` [changed in 5.1](https://make.wordpress.org/core/2019/01/14/new-styling-for-admin-table-pagination-links-in-wordpress-5-1/).

So, you're still outputting the old markup but for anyone using WP 5.1+, core's `/wp-admin/css/list-tables.css` is trying to style the new markup.  As a result, I get something that looks like the following screenshot:

![pagination](https://user-images.githubusercontent.com/3824560/55592516-e2967c00-56f5-11e9-8e99-30f96c02cfbf.png)

If there is a good reason to include you're own copy of `WP_List_Table`, you should also include (and enqueue) your own copy of `list-tables.css` (and dequeue core's version) from the same version of WP that you got `WP_List_Table`.

**Comment by pbiron** [comment]
BTW, I edited the source so that `MailAdminTable` extends core's `WP_List_Table` and as far as I can tell everything still works just fine (modulo #41 and #42).

**Comment by JWardee** [comment]
I'm on holiday atm, so will have a look through your issues in about a week or 2. Feel free to submit pull requests and review when I can :) just make sure they're PSR2 compliant

**Comment by JWardee** [comment]
I've always been in two minds about this. At the time it was done as per WordPress's documentation (https://codex.wordpress.org/Class_Reference/WP_List_Table) to avoid any changes to the class causing significant breakages.

But I do agree with you, neither approach will "solve" the issue of future proofing and extending from WP core's version of WP_List_Table would also significantly reduce the size of the plugin. So the plugin's copy of WP_List_Table will be removed in v1.2.4 :)

**Comment by JWardee** [comment]
Fixed in #46

**Comment by pbiron** [comment]
I downloaded the 1.2.4 branch, built it locally and can confirm that the list table pagination is now formatting correctly.
