### ISSUE TITLE
CSS styles bleed out into other pages

### ISSUE THREAD

**Issue by dazjohnson** [JWardee/wp-mail-catcher#44]
CSS needs to be namespaced to mail catcher. For example, there's a style on .field setting the height to 25px. This bleeds out and affects other parts of the WP backend, see attached.

Great plugin btw :D

![image](https://user-images.githubusercontent.com/25899495/55786066-71ffae80-5aab-11e9-8c46-a04ccf3f7072.png)

**Comment by JWardee** [comment]
Fixed in #45 please re-open if this is still an issue
