### ISSUE TITLE
composer autoload files missing from v1.2.4

### ISSUE THREAD

**Issue by pbiron** [JWardee/wp-mail-catcher#50]
I just updated to v1.2.4 from the wp.org repo and while the `wp-mail-catcher/vendor/composer` directory exists it is empty, and hence the plugin errors once reactivated.

Seems something went wrong when you built the zip for the wp.org repo.

**Comment by JWardee** [comment]
Ah thanks for letting me know, some files didn't commit to svn correctly - should be good to go now :)

**Comment by pbiron** [comment]
> Ah thanks for letting me know, some files didn't commit to svn correctly - should be good to go now :)

Worked like a charm!

p.s. don't take these recent issues I've opened as "complaints", I really like your plugin and it's been a big help to me on my local dev machine!!

**Comment by JWardee** [comment]
No problem at all, I'm very pleased you've found it useful!
