### ISSUE TITLE
Multisite: mail_catcher_logs table doesn't get deleted when the site is deleted

### ISSUE THREAD

**Issue by pbiron** [JWardee/wp-mail-catcher#51]
when run in a WP Multisite setup, when site/blog is deleted the `wp_N_mail_catcher_logs` table doesn't get deleted.

The easiest way to remedy this is to hook into the [wpmu_drop_tables](https://developer.wordpress.org/reference/hooks/wpmu_drop_tables/) filter and add it to the array of tables for core to drop.

**Comment by JWardee** [comment]
Thanks for the report, I'll try to reproduce and will fix in the next release!

**Comment by JWardee** [comment]
Will be released in v1.3.0 - please reopen if this is still an issue
