### ISSUE TITLE
Add 'From' Column

### ISSUE THREAD

**Issue by tothemoonsands** [JWardee/wp-mail-catcher#52]
Currently, there is no 'From' column displayed in WP Mail Catcher. One must click "More Info" to see this information.

Adding a 'From' column would allow easier viewing for received contact forms and other emails with the same subject line, that are only differentiated by the 'From'.

**Comment by JWardee** [comment]
In the next version I'll be adding which table columns can be shown or hidden into the 'screen options' dropdown. I'll make sure 'From' is one of the options, thank you for the suggestion!

**Comment by JWardee** [comment]
Added in 32cbdc7
