### ISSUE TITLE
Add Reply function

### ISSUE THREAD

**Issue by tothemoonsands** [JWardee/wp-mail-catcher#53]
Currently each email has three capabilities: Delete, Resent, or Export. Adding a Reply function would take advantage of this plugin's unique ability to create new messages. 

One clear use-case for this functionality is enabling shared access to responding to contact form inquiries.

**Comment by JWardee** [comment]
An interesting idea, would you envisiage this working?

I was thinking something like -

Clicking reply would open the 'new message' modal with the 'from' and 'to' values switched around, so if the previous message was from hello-from@example.com and sent to info@example.com then the reply would be from info@example.com and to hello-from@example.com, you could then fill out the other fields as normal and send the message - thoughts?

**Comment by JWardee** [comment]
Closed due to inactivity
