### ISSUE TITLE
Additional Headers in the "Detail" tab should be HTML escaped

### ISSUE THREAD

**Issue by pbiron** [JWardee/wp-mail-catcher#62]
The value of headers displayed in the _Detail_ tab when viewing an individual message from the logs list table should be HTML escaped.

For example, if a plugin sends an email and supplies a **From** header of the form:

> From: John Doe &lt;jdoe@example.com&gt;

All that currently displays is:

> From: John Doe

The fix is real simple, PR coming shortly.

**Comment by pbiron** [comment]
The PR is https://github.com/JWardee/wp-mail-catcher/pull/63

**Comment by JWardee** [comment]
Thanks for the PR!
