### ISSUE TITLE
Delete bulk action when applied from the "bottom" drop down doesn't do anything

### ISSUE THREAD

**Issue by pbiron** [JWardee/wp-mail-catcher#64]
When a user applies the **Delete** bulk action from the dropdown at the bottom of the list table nothing happens (i.e., the messages don't get deleted).

![bottom-delete-bulk-action](https://user-images.githubusercontent.com/3824560/61090697-bed18900-a3fc-11e9-8360-c06bac8c37ec.png)

PR with a fix coming shortly.

**Comment by pbiron** [comment]
The PR is https://github.com/JWardee/wp-mail-catcher/pull/65

**Comment by JWardee** [comment]
Will get this merged into v1.3.1
