### ISSUE TITLE
Css not prefixed and it hides data from other plugins

### ISSUE THREAD

**Issue by gabrieliuga** [JWardee/wp-mail-catcher#69]
Example plugin:
Facebook for WooCommerce
![image](https://user-images.githubusercontent.com/2194501/66387029-0abfaa00-e9bb-11e9-99b4-2919c45c66ab.png)

**Comment by JWardee** [comment]
Is the latest version of mail catcher being used? It's already namespaced 

https://github.com/JWardee/wp-mail-catcher/blob/a426ba36b0e477c301009abb6ef8cb630f9c0f47/build/scss/admin.scss

**Comment by JWardee** [comment]
Previous related issue

https://github.com/JWardee/wp-mail-catcher/issues/44
