### ISSUE TITLE
Multisite: when network-active, should create the mail-catcher table when a new blog is created

### ISSUE THREAD

**Issue by pbiron** [JWardee/wp-mail-catcher#70]
This is the flip-side of #51.  I thought I reported this at the time I reported that other issue, but see that I didn't.

I can do a PR.

One question before I put together the PR: you still want to support back to WP 4.7, correct?  I ask because the action to hook into is different for WP < 5.1 and >= 5.1.

**Comment by JWardee** [comment]
Yes please, if you add in both actions then we'll be good to go

**Comment by JWardee** [comment]
Perfect thanks for the PR, I messed up merging it so please ignore any merge requests I've made in your fork
