### ISSUE TITLE
Settings.php line 62

### ISSUE THREAD

**Issue by oginomizuho** [JWardee/wp-mail-catcher#76]
In Settings.php line 62.
I think it should be $settings['default_settings_role'].
It would be appreciated if you fix it in next update.

Thanks for your great plugin!

**Comment by JWardee** [comment]
Hey, glad you like the plugin! Thanks for the report and you're right it should be `$settings['default_settings_role']` I'll deploy a fix in the next version

**Comment by JWardee** [comment]
Fixed in c79ae0a will be released in v1.3.6
