### ISSUE TITLE
Logs per page option is ignored in the options manager

### ISSUE THREAD

**Issue by JWardee** [JWardee/wp-mail-catcher#87]
https://wordpress.org/support/topic/pagination-number-of-items-per-page-problem/

**Comment by sinasaeedi** [comment]
WordPress: 5.4.2
WordPress Language: Persian (Farsi)
SSL: Yes
Server: Windows
Web Server: Apache 2.4.43 
PHP: 7.4.7
MariaDB: 10.4.13

Any other details?

**Comment by JWardee** [comment]
That's perfect, thank you. I've just tested this on my local and can replicate the issue so it'll be fixed in the next release :rocket:

**Comment by JWardee** [comment]
Fixed in ab6fd70

**Comment by sinasaeedi** [comment]
Great, well done!
