### ISSUE TITLE
Resending email formatting

### ISSUE THREAD

**Issue by JWardee** [JWardee/wp-mail-catcher#97]
https://wordpress.org/support/topic/resend-html/

**Comment by JWardee** [comment]
Unable to replicate, resending html emails correctly send the html

**Comment by pacmanito** [comment]
Please investigate this matter further as I am getting this bug right now.

**Comment by JWardee** [comment]
As mentioned before I wasn't able to replicate the issue so I need more information. What sort of emails aren't working correctly? What headers are you using on them? Is this an email initially sent using mail catcher or something else.

I need to be able to replicate the issue my end or I won't be able to fix it

**Comment by pacmanito** [comment]
There's a WooCommerce email which was not sent due to some technical issues (SMTP authentication error). Such email is marked with a red dot on main screen of WP Mail Catcher. I hit resend button and if email is plain text then it looks OK in receiver's inbox but if email is HTML it is delivered as blank letter with attachment containing HTML. As mentioned by original topic starter at WP forum this resent email looks OK in WP Mail Catcher itself (using "more info" button).
BTW to send emails I am using SMTP.

**Comment by JWardee** [comment]
Thanks for the info, that's much more helpful. 

Could you paste what the headers the message was being sent with. You can get this either through your email client or Mail Catcher (more info button). 

I'll let you know if I can replicate, probably some point next week

**Comment by pacmanito** [comment]
Thanks for spending your time on this free plugin.
Do you mean this?
`Content-Type: multipart/alternative`
That's the only useful information I see through "more info" button.

**Comment by JWardee** [comment]
Ah yes, that header isn't right which is why the html isn't being parsed correctly by the email client. Is this header from the original WooCommerce email or is it from the one resent by mail catcher?

**Comment by pacmanito** [comment]
I suppose this is the same header as the one of original email. But I suppose it's legit as it's used for any email contaning both HTML and plain text versions.

**Comment by JWardee** [comment]
I haven't been able to replicate the issue, whenever an email is resent it'll use whatever headers were initially set. So if the original email has `Content-Type: multipart/alternative` then the resent version will have the same.

Whatever you're using to send emails out (either code - like below or a plugin) is setting the content type header to be `multipart/alternative` which is causing your email client to render the message incorrectly. The Mail Catcher details screen will always assume its html or plain text so it'll always render it correctly. So it's nothing to do with Mail Catcher unfortunately.

I did find a minor issue which I've resolved and will be releasing in 1.5.4 pretty soon. But I'm not convinced it'll resolve your issue.

```
$to = 'sendto@example.com';
$subject = 'The subject';
$body = 'The email body content';
$headers = array('Content-Type: text/html;');

wp_mail( $to, $subject, $body, $headers );
```

If you can reliably recreate the issue using and it's a result of Mail Catcher on a fresh WP installation then open up a new issue with the exact steps and I'll take another look :)

**Comment by pacmanito** [comment]
Hi, the problem still exists. I studied the code of original and resent emails and they are different. One obvious thing is that email resent by plugin is lacking plain text part, it has only HTML. I suppose it would be benefetial if I could sent you the code of this emails privately, can you please give me an idea how I can do that?

**Comment by pacmanito** [comment]
@JWardee please check this one, as I am rather sure there's a problem (check my previous message). Maybe it's related to https://github.com/JWardee/wp-mail-catcher/issues/122
