### ISSUE TITLE
Text not properly formatted in debug view

### ISSUE THREAD

**Issue by pacmanito** [JWardee/wp-mail-catcher#98]
Hi, when I view message in debug view (more info -> debug) the text is not properly formatted if it's long enough.
Please see for clarification - 
![image](https://user-images.githubusercontent.com/56888134/111971455-6cbb9300-8b0d-11eb-822c-ddfed1246153.png)

P.S. Many thanks for all the efforts to create this usefull and lightweight plugin

**Comment by JWardee** [comment]
Thanks for the report, when I get a chance I'll check it on my local, if I can replicate it it'll be fixed in the next update!
