### ISSUE TITLE
Undefined offset PHP notice

### ISSUE THREAD

**Issue by pacmanito** [JWardee/wp-mail-catcher#99]
Hi again. The plugin triggered following PHP notice:
`Undefined offset: 1 in /wp-content/plugins/wp-mail-catcher/src/Models/Mail.php on line 124`

So far I was not able to reproduce the issue.

**Comment by JWardee** [comment]
Thanks for the report, when I get a chance I'll check it on my local, if I can replicate it it'll be fixed in the next update!

**Comment by JWardee** [comment]
Not able to reproduce, please open another issue if you can recreate this :)
